apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/balusena/argocd-helm-kustomize-rollouts-blue-green.git
    targetRevision: HEAD
    path: helm/myapp
    helm:
      valueFiles:
        - ../../overlays/prod/values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-myapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
